### ISSUE TITLE
Room label issues

### ISSUE THREAD

**Issue by daagar** [Chris7/3k-Scripts#6]
A few issues with room labels in the current script:
- Typo in alias "Delete a Label": line 20, lTabel instead of lTable in elseif statement
- Need to cast 'id' as a number in tmap:deleteRoomLabel()

Requests/Suggestions:
- Make label font size a configurable value
- Make tmap:_label_ command be able to interact with default generated map labels. For example, when creating a new special exit the label that gets created isn't recognized by 'tmap deletelabel'. It must be deleted via right-click->delete on the map window itself.

**Comment by Chris7** [comment]
Should all be fixed, thanks for the bugs in deleting labels.
